### ISSUE TITLE
Add keyboard bindings to colour interactives with sliders

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#357] opened 2016-06-10 07:14 UTC
## Description

It would be useful to add bindings to all sliders in colour interactives to precisely select values. Right and up arrow keys should increment values by one, and left and down arrow keys should decrement values by one.
### Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the issue._
- [x] I have linked any relevant [existing issues/suggestions](https://github.com/uccser/cs-field-guide/issues) in the description above (include `#???` in your description to reference an issue, where `???` is the issue number)
- [x] I have applied relevant labels

**Comment by JackMorganNZ** [comment] 2016-06-10 10:13
This example will be helpful for implementing this feature: http://refreshless.com/nouislider/examples/#section-keyboard

**Comment by eAlasdair** [comment] 2019-05-30 00:13
Duplicate of #496, closing this one because the other is worked on

**Closed by eAlasdair** 2019-05-30 00:13 UTC
Labels: interactives, suggestion
