### ISSUE TITLE
Handle translations of interactives

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#71] opened 2015-07-22 00:16 UTC
Each interactive should be able to accept a translation file (possibly a .csv or .conf file) for viewing it in different languages.

**Comment by JackMorganNZ** [comment] 2016-06-27 01:22
Thoughts for storing translations in CSV format:
- Easy to edit for users (doesn't require understanding of a more complex syntax like JSON)
- Can easily view on GitHub
- Can import into interactives using JS libraries ([PapaParse](https://github.com/mholt/PapaParse) looks great).

**Comment by JackMorganNZ** [comment] 2016-06-27 01:24
A template file should added to the interactives `base-files` folder (#2) in order to complete this task.

**Comment by eAlasdair** [comment] 2019-05-30 23:18
Duplicate of #2 :noot-noot:

**Closed by eAlasdair** 2019-05-30 23:18 UTC
Labels: interactives, internationalization, review needed
